### ISSUE TITLE
outbound and inbound does not match capacity by 34% in Channel Rebalancing 

### ISSUE THREAD

**Issue by RemoRitzmann** [cryptosharks131/lndg#119]
![image](https://user-images.githubusercontent.com/8985954/181907836-ea331a27-12d8-4ebb-af39-44a393244d9f.png)

When I count Bcash_Is_Trash's outbound and inbound together, I get 583400 + 82463 = 665863, but it's capacity is 1,030,000
Do I miss something or is this an issue? 

Another example is:
![image](https://user-images.githubusercontent.com/8985954/181935766-7562bc34-3a4b-4df8-ad12-2d20ec93e8df.png)

**Comment by cryptosharks131** [comment]
The amounts here are not including any amount that have pending HTLCs. The pending amount could be added to either side so that it then matches the percentages.
