### ISSUE TITLE
Allow "open channel" to work with just remote_pubkey

### ISSUE THREAD

**Issue by asvdf** [cryptosharks131/lndg#13]
To the extent of opening a channel, unless it is an additional channel to an existing peer, it is currently needed to connect to the relevant peer, and then add them via pubkey.
This is naturally feasible by the human node operator, by fetching the needed data and executing the two operations in tandem, yet this might also be scripted, so that the operator will just input the remote pubkey of the node, and if not already among connected peers, LNDg will fetch the full connection string, connect to the peer, and then open.
This could be achieved querying the graph info, rather than parsing remote services like amboss.space or 1ml, for privacy and autonomy.

**Comment by cryptosharks131** [comment]
Coming soon in the next release https://github.com/cryptosharks131/lndg/commit/080a3ac8495eea72d9a6fe60d61b265a3186356e

**Comment by asvdf** [comment]
oh sorry for not checking first, closing issue then!
