### ISSUE TITLE
Not starting when GUI-NetLinks is not available

### ISSUE THREAD

**Issue by steff123** [cryptosharks131/lndg#136]
Hey,
I changed  GUI-NetLinks to my local mempool.space instance on runcitadel (IP:PORT). But the port had changed in the last update of citadel. Because of this I was not able to start lndg

```
Error getting closure fees for 03bba884fe9f8d33c1a91e2af8e24d348347b482ba342a9876e58ad84ba400c3 - HTTPConnectionPool(host='192.168.2.167', port=3044): Max retries exceeded with url: //api/tx/03bba884fe9f8d33c1a91e2af8e24d348347b482ba342a9876e58ad84ba400c3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f98352f0220>, 'Connection to 192.168.2.167 timed out. (connect timeout=None)'))
```

After an update with sqlite, I could start lndg
```
UPDATE gui_localsettings SET value="http://192.168.2.167:3050/" where key="GUI-NetLinks"
```

**Comment by cryptosharks131** [comment]
The UI will still load, even if the settings value is not working for the fees and you should have still been able to edit from the `/advanced` page.

The error you saw was just a warning that the migration couldn't get the fees and sets it to zero instead.
https://github.com/cryptosharks131/lndg/blob/master/gui/migrations/0030_auto_20220722_0912.py#L20-L26

Feel free to reopen with more details if you believe there is something more going on here!
