### ISSUE TITLE
Update in settings fails with NGINX

### ISSUE THREAD

**Issue by ursus-caerulus** [cryptosharks131/lndg#139]
I have used the NGINX reverse proxy to encrypt my lndg traffic and use port 8899 instead of 8889.

When altering setting, the following link fails https://xxx.xxx.x.xx:8899/update_channel/ 

Is there a way around this, or is the best option to remove the NGINX reverse proxy?

**Comment by cryptosharks131** [comment]
Are you seeing any errors? The only particular thing about this URL is that it is a POST request route.

**Comment by ursus-caerulus** [comment]
The page does not redirect correctly 
Error connecting to xxx.xxx.x.xx:8899. 
This problem can sometimes be caused by disabling or refusing cookies.

I have used incognito mode as well, to ensure no addon is prohibiting any cookings being used.
