### ISSUE TITLE
Autopilot and AR-Inbound%

### ISSUE THREAD

**Issue by xmready** [cryptosharks131/lndg#167]
Does autopilot automatically set a reasonable `AR-Inbound%` upon enabling AR? I see the default is `100%` so i'm curious if a channel is enabled by AP, does this value get set based on some logic so it can be re-balanced?

**Comment by Bitcoinite** [comment]
No it doesn't. AR-Inbound% and AR-Outbound% are the base settings for new channels. You need to set the corresponding iTarget% and oTarget% manually for all channels, depending on if it's a source/sink/router. AP doesn't do this for you. AP is only for automatically enabling/disabling AR.

If AR is enabled --> LNDg will look at iTarget% and rebalance into the channel until this threshold is reached
If AR is disabled --> LNDg will look at oTarget% and push out of the channel until this threshold is reached

So for sources you want low oTarget% and 100% iTarget%
For sinks you want low iTarget% and 100% oTarget%
For routers you might want to try out which settings are working for you
