### ISSUE TITLE
Show information about forwards that failed downstream

### ISSUE THREAD

**Issue by joostjager** [cryptosharks131/lndg#182]
Currently lndg shows information about failures that originated from the node running lndg at `/failed_htlcs`. It would be great if it is also possible to show all failures including the ones that originated further downstream. With that, node operators can get a sense of how much htlc spam their node is processing.

Downstream failures are currently filtered out here:

https://github.com/cryptosharks131/lndg/blob/57019b9755fee5dfee6480c34e14554a2846a5d9/htlc_stream.py#L16

For downstream failures, `link_fail_event` is empty.

**Comment by cryptosharks131** [comment]
The only issue I foresee here is that the amount of records that will get written to the db are extremely high when watching the full stream.

What does a node do with this information or if they find they are handling a lot of failed htlcs not caused by themselves?

**Comment by joostjager** [comment]
There are a number of things that they can do with this information. They could for example find out from which peer the bulk of the traffic is coming, and contact the peer and/or close that channel. Or when using something like https://github.com/lightningequipment/circuitbreaker, they could lower the rate limit for that peer.

Insights into all failed forwards and the development of that over time can also be useful to plan ahead in terms of hardware and disk space.

I see your concern about high volumes, although the lnd channel database itself will grow in a similar way. So in total, the disk space requirement will still be on the same order of magnitude. Perhaps a suitable way to deal with this is to aggregate the failures per in/out pair on an hourly basis, and write only that count to disk.

**Comment by joostjager** [comment]
Another solution to the disk space problem is it simply only keep the failures of the last hour. No trends over time visible, but at least as an operator you can get a sense for the volume of spam that you are facilitating

**Comment by joostjager** [comment]
I don't know if this is a direction that you'd like to go into, but it is also a possibility to allow the user to set limits on htlc rates and slots occupied. Basically integrating firewall functionality into lndg.

**Comment by zx9r** [comment]
To avoid db issues pointed by @cryptosharks131 this could be made as an optional feature. With a single toggle button, users could choose to opt-in or out to enable/disable this htlc failure events.
