### ISSUE TITLE
Sign commits using gpg keys

### ISSUE THREAD

**Issue by niteshbalusu11** [cryptosharks131/lndg#188]
Since lndg is now very popular and used a lot and it has access to admin macaroon, it'll be better if all commits made to this repo are signed by your personal gpg keys to make sure commits are authentic.

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by cryptosharks131** [comment]
This should be the case going forward and starting with v1.5.0!
https://github.com/cryptosharks131/lndg/commits/v1.5.0
