### ISSUE TITLE
Incorrect onchain balance while channels waiting to close

### ISSUE THREAD

**Issue by jtymoszczuk** [cryptosharks131/lndg#194]
i noticed total balance is double counting uncofirmed balance. 

Total Balance = Onchain + Funds in Channel + unconfirmed balance

unconfirmed balance is already included in Onchain balance. If unconfirmed is accounted for in the "onchain balance" it should be:

Total Balance = Onchain + Funds in Channel

**Comment by cryptosharks131** [comment]
This seems to occur during co-op closures while channel is Waiting to Close. This is due to the closing balance in this state being in both the pending onchain balance and the limbo balance. Potentially can exclude limbo balance from the channels waiting to close list as a remediation.
