### ISSUE TITLE
Historical data loading very slowly

### ISSUE THREAD

**Issue by ssurfertuga** [cryptosharks131/lndg#197]
Hey guys,

Installed a fresh LNDg 1.5.0 and after everything was working and running (as per instructions) I noticed the main page (My LND Overview) was displaying Last X Payments Routed, Last X Payments Sent and Last X Payments Received from more than 3 months ago. Now it shows 2 months and 3 weeks. It seems it's very slowly catching up to the current time.
I never seen this behaviour in previous versions of LNDg.

Anyone has a clue about this? Could it be a bug?
Is there a way to maybe reset the database information collected at first run?

LND version: 0.15.5 beta
Linux: Ubuntu 20.04

<img width="1100" alt="Screenshot 2023-01-27 at 11 25 43" src="https://user-images.githubusercontent.com/8077390/215155051-c768e3b2-b513-45df-b477-451888d5de79.png">
<img width="1100" alt="Screenshot 2023-01-27 at 11 26 06" src="https://user-images.githubusercontent.com/8077390/215155067-4e1c2cb4-af24-4f71-a4b9-214301dfd05c.png">

**Comment by cryptosharks131** [comment]
It can take a bit to reload all your previous data, do the records continue to slowly come in?

**Comment by ssurfertuga** [comment]
> It can take a bit to reload all your previous data, do the records continue to slowly come in?

Well it still shows 2 months, 3 weeks ago. At this rate it will take another 2 months to correctly show the information.
Also I noticed earnings and costs (vital information for me to correctly configure rebalances) display 0 sats. As per screenshot below.

<img width="1142" alt="Screen Shot 2023-01-27 at 13 03 53" src="https://user-images.githubusercontent.com/8077390/215174407-3ad0e577-6e7f-4688-9e1b-60c4bcf29f76.png">

Is there a way to accelerate this process? Maybe using the command line?

**Comment by cryptosharks131** [comment]
I think there are some items here to address that would help historical data load faster.  In the mean time, the only thing that I can think of that might help would be to manually clean up any failed payment data from LND that might be getting processed.  You could do this with command line using lncli or bos.

**Comment by ssurfertuga** [comment]
> I think there are some items here to address that would help historical data load faster. In the mean time, the only thing that I can think of that might help would be to manually clean up any failed payment data from LND that might be getting processed. You could do this with command line using lncli, bos or the standalone `delete_payments.py` script in the lndg app folder.

Thanks for your help! After cleaning the failed payments, it took a lot of hours but the data is now close to reach today's date. I guess 12 more hours and all will be in sync.
