### ISSUE TITLE
JS Bug with dark mode

### ISSUE THREAD

**Issue by prolic** [cryptosharks131/lndg#254]
If you try to hit the "toggle dark mode" button, nothing happens. In the browser console you'll see this error instead:
```
Uncaught ReferenceError: darkMode is not defined
```

**Comment by cryptosharks131** [comment]
Can you provide the version of lndg and browser you are using?

Did you recently update from an older version? You can also try reloading the page without caching.

**Comment by prolic** [comment]
LNDg v1.5.1 using Firefox Browser on Linux

**Comment by prolic** [comment]
I tried again using latest 1.6.0 release from yesterday

![Screenshot_20230330_135022](https://user-images.githubusercontent.com/394428/228921990-67be1567-3c76-4f30-8605-f61aafca3349.png)

**Comment by prolic** [comment]
Ok this ` .venv/bin/pip install whitenoise && rm lndg/settings.py && .venv/bin/python initialize.py -wn` did the trick for me. I was using your tool without any of the fancy UI/JS/CSS stuff all the time, lol. Thanks.
