### ISSUE TITLE
datetime 64 error

### ISSUE THREAD

**Issue by caiomsbr** [cryptosharks131/lndg#266]
An error has occured!
Error Code: datetime64 type does not support sum operations

I started to receive this message as soon as log in into lndg overview, the login screen does work though. I'm currently running LNDg using mynodebtc platform, I tried reinstalling lndg, rebooted number of times but the error remains. 

I don't know If there is some persistent config file that reinstallation isnt deleting!

Does anyone have a clue on how to solve this?

**Comment by cryptosharks131** [comment]
This is solved in the updated release `v1.6.3`. Are you able to pull the latest release on myNode?

https://github.com/cryptosharks131/lndg/releases/tag/v1.6.3

**Comment by caiomsbr** [comment]
Oh.. excellent, thank you for your time, I'm gonna wait the update to come up on mynode!!
