### ISSUE TITLE
AF-Enabled input does not exists

### ISSUE THREAD

**Issue by rcorba** [cryptosharks131/lndg#275]
Hi, I am on LNDg v1.6.3, there is no possibility to enable Auto Fees or I cannot find it. 

On page /fees in section "Auto-Fees Settings" setting "AF-Enabled" (that used to be there) disappeared and I see now other place where it can be set.

**Comment by cryptosharks131** [comment]
Thank you for reporting this, it looks like we forgot to add this switch to the updated AF form.

You can manually adjust this value using the api in the mean time.
`/api/settings/AF-Enabled/`

**Comment by rcorba** [comment]
oh thank you, it is very good to know
