### ISSUE TITLE
rebalances almost stopping

### ISSUE THREAD

**Issue by patripb** [cryptosharks131/lndg#277]
Hi! 
Im running 1.6.3 and since yesterday my rebalance not working properly. Very few rebalances. Im facing like 4 hours without any rebalance. Saw nothing strange on my lndg logs.

**Comment by cryptosharks131** [comment]
Can you check and see what the last statuses are on your failed rebalances (bottom table)?
`/rebalances`

**Comment by patripb** [comment]
in the meantime I downgraded to 1.6.1, rebalances worked and then stopped at all.  All status are timout or rebalancer-request-timeout
