### ISSUE TITLE
Truncated keysend=true transaction messages

### ISSUE THREAD

**Issue by blakejakopovic** [cryptosharks131/lndg#28]
On http://server:8889/keysends/, for transactions with keysend=true, messages with larger than 255 characters are truncated. I can't find a documented max keysend length, however I'd like to propose it is increased.

This seems to be the only place in the source that would need updating.
https://github.com/cryptosharks131/lndg/blob/f3ba04df988d9654b6383b1afc24b3282ddd80ed/gui/models.py#L44

**Comment by cryptosharks131** [comment]
This should not be an issue to implement in an upcoming version.  It looks like the max payload size for a payment would be 1300 bytes and message lengths depend on what characters the user puts in the message. Increasing the max size to somewhere in the 500 or 1000 character limit may be more fitting.

We would also need to update here, when saving the message to the database.
https://github.com/cryptosharks131/lndg/blob/f3ba04df988d9654b6383b1afc24b3282ddd80ed/jobs.py#L98

**Comment by cryptosharks131** [comment]
Resolved in #40
