### ISSUE TITLE
502 BadGateway

### ISSUE THREAD

**Issue by EagleEye911** [cryptosharks131/lndg#285]
After updating my raspiblitz to the newest version of LNDG I get an Bad Gateway nginx message on my normal browser and tor browser. My nginx logs looking normal.

**Comment by cryptosharks131** [comment]
502 usually means that uwsgi or gunicorn is not running properly. Try to check on the status and logs for this service.

**Comment by EagleEye911** [comment]
Thank u. I restarted the services and everything works fine.
