### ISSUE TITLE
What do the "Successful Payments Routed" and "Amount Routed" columns on the "Opens" page mean?

### ISSUE THREAD

**Issue by andreashuber69** [cryptosharks131/lndg#286]
The values shown in the **Successful Payments Routed** and **Amount Routed** columns seem to be off by at least an order of magnitude. Compare these to the P&L for my node. What am I missing?

![Screenshot from 2023-05-13 19-49-19](https://github.com/cryptosharks131/lndg/assets/7470215/7665a3bc-7266-48a6-8682-1a5bb4bcfe87)

![Screenshot from 2023-05-13 19-51-11](https://github.com/cryptosharks131/lndg/assets/7470215/accdd3c3-10b1-490f-abf7-7c2a8f3d2e0f)

**Comment by cryptosharks131** [comment]
There is an issue in the current version that is counting stale in-flight payment routes in the calculations on the Opens page.

This will be resolved in the next release!
