### ISSUE TITLE
Login not working with lndg-admin

### ISSUE THREAD

**Issue by MichaelAntonFischer** [cryptosharks131/lndg#288]
Hi,

I am having trouble accessing the GUI. In the data folder, the file lndg-admin.txt was created, but the password is not being accepted by the GUI, when trying to login. Any ideas?

![Image 30 05 23 at 15 17](https://github.com/cryptosharks131/lndg/assets/93607398/f940b12f-e9e5-4aed-ab1d-16a50fd5b3f7)

**Comment by MichaelAntonFischer** [comment]
Tried also with -u and -pw options, still same behavior.

**Comment by MichaelAntonFischer** [comment]
Hi,
sorry for late response. Was traveling. Is there a way to set it to 'all'? I am always using a vpn so it's hard to correctly set this up.

**Comment by cryptosharks131** [comment]
Try using a `*` when passing the CSRF argument.
`initialize.py -csrf "*"`

**Comment by cryptosharks131** [comment]
Ahh looks like the script is missing the quotations needed here, can you try it like this?
`initialize.py -csrf "'*'"`
