### ISSUE TITLE
[FEATURE] Add option to run in isolated environment without `lnd.conf`

### ISSUE THREAD

**Issue by jblachly** [cryptosharks131/lndg#29]
All components of my lightning stack are running in separate VMs (actually LXC containers).

AFAICT, lndg needs RPC info from `lnd.conf` and `admin.macaroon`.

Please consider an `lndg.conf` with just RPC credentials and the name of an arbitrary macaroon (for example, I may wish to use the `readonly` caveat)

Thank you!

**Comment by cryptosharks131** [comment]
The only things that lndg needs to run is a valid tls and macaroon file.  The settings for lndg are all found inside `lndg/settings.py`.

In this case, you could bake your own macaroon and rename it to admin.macroon.  Then place this and the tls.cert into a folder structure that matches a lnd directory (all subfolders can be empty except for these two files).

Then use the `-dir` flag of initialize.py or update your  settings.py `LND_DIR_PATH` variable to the isolated directory.

**Comment by jblachly** [comment]
Awesome, thanks. I'll leave this open and try to make a PR for the documentation.

**Comment by cryptosharks131** [comment]
Closing as in `v1.4.0` you may now specify a custom path to your macaroon and tls files.
