### ISSUE TITLE
Seeing datetime error on main page

### ISSUE THREAD

**Issue by reboted** [cryptosharks131/lndg#292]
I'm getting a datetime error when opening the main page in browser:

"An error has occured!
Error Code: datetime64 type does not support sum operations"

LNDG is deployed on latest Raspiblitz release 1.9.0.  Looks like it might be pandas related.

**Comment by cryptosharks131** [comment]
Try updating LNDg through the Raspiblitz interface, I think it installs v1.6.0 which had this issue but updating to v1.6.4 will solve it.

**Comment by reboted** [comment]
Yep, that fixed it.   Thx!
