### ISSUE TITLE
Wrong public node capacity in case of inactive channels

### ISSUE THREAD

**Issue by feelancer21** [cryptosharks131/lndg#308]
Hey, I updated from 1.5 to 1.7.1 this week. I observed a wrong public node capacity if one channel is inactive. Imho in this case only the capacity of the inactive channel is counted for the public node capacity.

**Comment by cryptosharks131** [comment]
I am unable to replicate the issue here.

Public capacity should remain constant regardless if peers are active or not and match what public explorers are reporting for the node.
