### ISSUE TITLE
available outbound liq. is diferent between chans & failed HTLCs

### ISSUE THREAD

**Issue by proof-of-reality** [cryptosharks131/lndg#335]
failed htlc table:
![image](https://github.com/cryptosharks131/lndg/assets/43297242/87bdebd2-c4a6-4934-9a18-d276832690fa)
chans table:
![image](https://github.com/cryptosharks131/lndg/assets/43297242/e61f2491-8527-43a8-a3d2-2d34ae5fb85d)
on the same channel

**Comment by cryptosharks131** [comment]
The value in failed htlc is reduced by the channel reserve amount (1% of capacity), as it can't be utilized and will cause payments to fail for insufficient balance
