### ISSUE TITLE
Either fees calculated wrong or Amount in/out are dissplayed in the wrong way

### ISSUE THREAD

**Issue by endurance1968** [cryptosharks131/lndg#336]
![2023-10-30_08h08_11](https://github.com/cryptosharks131/lndg/assets/38796027/5c24710a-b353-49ee-aece-c4744dc70101)

Looks like . should be , or the fees are wrong. Doubled in/out but 1000x less fee then I would expect.

Using lndg 1.7 on umbrel (ubuntu).

**Comment by cryptosharks131** [comment]
What language setting is the browser you are viewing from using?
