### ISSUE TITLE
LNDG Automated channel rebalancing not working:

### ISSUE THREAD

**Issue by BonzoDogDooDah** [cryptosharks131/lndg#339]
Hi,

we have been using the LNDG app in Umbrel for awhile now and love the user interface and use it often to maintain our node but we have never been able to get it to function as an auto rebalancer no matter what the combination we try, even when the sat amount is very low and the other tabs are also set low etc,,, Please help.  Thank you :)

**Comment by proof-of-reality** [comment]
Hi @BonzoDogDooDah, have you set `AR` to `true` in the UI?

**Comment by cryptosharks131** [comment]
Check the `/rebalancing` page to help visualize what channels are being used for Out/In and verify you have at least one Out and one In channel.

Also check the `AR Max Fee Rate` is high enough to rebalance your channels. The default is 100 ppm and many channels require a higher fee than this to rebalance. This value is a global cap for all rebalances.
