### ISSUE TITLE
[Feature request] Add option to disable channels

### ISSUE THREAD

**Issue by Darth-Coin** [cryptosharks131/lndg#34]
Yes, is not good to disable channels (prohibit traffic through) temporarily, is almost against the meaning of LN.
But sometimes you want for specific reasons to route traffic only through specific channels.
So will be good to have an option, a tick box or something to disable a channel and re-activate it when is necessary.
I know that `updatechanstatus` is removed when the node is restarted but that is OK.

**Comment by cryptosharks131** [comment]
Resolved in #40
