### ISSUE TITLE
LNDg cannot reach the gRPC for LND. 

### ISSUE THREAD

**Issue by 25shmeckles** [cryptosharks131/lndg#348]
I am running the latest docker image on Linux Mint 21.2 Cinnamon

I get the following error after logging in to the server.

```
An error has occured!
LNDg cannot reach the gRPC for LND. Make sure LND is running and/or your gRPC settings are correct.
Error Code: StatusCode.UNAVAILABLE
```
![Screenshot from 2023-12-03 18-17-42](https://github.com/cryptosharks131/lndg/assets/25845049/adac2388-f104-49e8-acae-a4957be81ca5)

LND is running just fine as well as other tools, like RTL and loop. So the gRPC settings on LND should be correct.
I can't find anything relevant on the docs to solve this. Any help is welcome.

**Comment by cryptosharks131** [comment]
Are you also running LND in a docker container?

**Comment by 25shmeckles** [comment]
Yes

**Comment by 25shmeckles** [comment]
From local works, although the GUI has some issues. But from the container it is not communicating with LND.

Here is the odd rendering of the local GUI. No colored bars, weird alignments, the `Toggle dark mode` button doesn't work.

<img width="1449" alt="Screenshot 2023-12-11 at 11 59 14" src="https://github.com/cryptosharks131/lndg/assets/25845049/d157fd5d-8035-4e6e-942b-2d180f75c13c">

**Comment by cryptosharks131** [comment]
Networking between docker containers can be complex unless they are running on the same docker virtual network. You can add the docker network LND is using to your LNDg docker-compose.yaml so they can communicate on the same host or let LND listen on your machine IP and accept requests from the docker network LNDg is using. You can also try running the LNDg container with `network_mode: "host"` or run LNDg without Docker.

The rendering issue looks like you are missing the required css files. Usually this is not an issue for docker installations, maybe check the dev tools page of your browser to see if there are any issues loading those static files.

**Comment by Heebron** [comment]
Is there a debug flag I can set? I just updated my local instance following the below and can no longer connect to LND upon restart. I get the error titling this ticket.

```
docker-compose down
git pull
docker-compose build --no-cache
docker-compose up
```
I run without the _-d_ hoping to see some indication describing why the connection fails. Nothing pops up.

I am very familiar with docker and overlay networking but don't run my lnd in a container.

**Comment by cryptosharks131** [comment]
You can enable the django debug mode with the `-dx` flag but I'm not sure it will give you any additional information in this case.

**Comment by Heebron** [comment]
It told me just enough. Thanks.  I recently changed my DNS cache from dnsmasq to AdGuardHome. The problem was in the way AdGuardHome handles things vice dnsmasq. Have a Happy and Safe New Year!

**Comment by psisoyev** [comment]
I'm facing a similar issue. I've put both LND and LNDg in the same docker network but can't establish a grpc connection:
```
lndg  | Migration step failed: <_InactiveRpcError of RPC that terminated with:
lndg  | 	status = StatusCode.UNAVAILABLE
lndg  | 	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.3:10009: Peer name lnd is not in peer certificate"
lndg  | 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:172.18.0.3:10009: Peer name lnd is not in peer certificate", grpc_status:14, created_time:"2024-01-07T13:35:34.315727546+00:00"}"
lndg  | >
```

I've tried to pass certificates explicitly using flag `-tls` but had no luck. Any hints?

**Comment by cryptosharks131** [comment]
I have not seen this error before, do you want to share how you setup your docker networking?

**Comment by psisoyev** [comment]
It was my mistake at the end. I've misconfigured TLS certificates for LND/LNDg.

What one should do is to create/edit `lnd.conf` for LND and add there 
```
tlscertpath=/etc/lnd-tls/tls.crt
tlskeypath=/etc/lnd-tls/tls.key
```
This certificate should be generated beforehand and mounted as a volume (for my test environment I'm using simple self-signed certificate) to the container. 
The same certificate should be passed to LNDg and passed as an argument to LNDg:
```command: ["sh", "-c", "python initialize.py -net 'simnet' -tls '/etc/lnd-tls/tls.crt' -server 'lnd:10009' -d && supervisord && python manage.py runserver 0.0.0.0:8000"]```
One should also add the DNS name to the certificate and then it should all work well
