### ISSUE TITLE
RFE: night mode

### ISSUE THREAD

**Issue by thejerrod** [cryptosharks131/lndg#35]
my eyes!

**Comment by SuperAtic** [comment]
Suggestion: Maybe easier to have a script that detects the system color-scheme and change the Ui automagically by default... something like [this](https://github.com/Darth-Knoppix/safari-theme-css). However, the functionality can/should also be customised on a User Preferences/Settings

**Comment by cryptosharks131** [comment]
Good idea, we could certainly add a setting for that to the database.

**Comment by GaryBanderas** [comment]
In the meantimes, there is browser extensions that can do that like Dark Reader.

**Comment by Bitcoinite** [comment]
I would like to bump this issue. It would be really nice to see this added. This would decrease the number of mosquitos attracted by my monitor at night by a lot!
