### ISSUE TITLE
Manual installation + Ubuntu Server + Lightning Terminal

### ISSUE THREAD

**Issue by igorbastosib** [cryptosharks131/lndg#367]
Hello guys,
I'm trying the manual installation on an Ubuntu Server + Lightning Terminal, the LN is running perfectly all good.

Following this [tutorial](https://raspibolt.org/guide/bonus/lightning/lndg.html) for LNDg I get the following error 
**Error initializing django: [Errno 2] No such file or directory: '/home/lndg/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'**

This happens while running the command: **.venv/bin/python initialize.py -wn**

The tutorial says to create a new user and etc... The issue just happens if I create the new user. If I follow the process on the same user that LND is installed, the issue doesn't happen.

Any ideas?

I'm a newbie playing with to learn about LN stuff

**Comment by cryptosharks131** [comment]
It seems that the macaroon file is not located at `'/home/lndg/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'` or the user you are using to run LNDg does not have access to it.  Verify that your macaroon exists there and also that you have permission to read it.

If you need a custom path to the macaroon, you can use `.venv/bin/python initialize.py -h` to see all the available customization options available.

**Comment by igorbastosib** [comment]
> It seems that the macaroon file is not located at `'/home/lndg/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'` or the user you are using to run LNDg does not have access to it. Verify that your macaroon exists there and also that you have permission to read it.
> 
> If you need a custom path to the macaroon, you can use `.venv/bin/python initialize.py -h` to see all the available customization options available.

Ty for your reply.
You got it right, it was permission issue (also hyper link issue).
