### ISSUE TITLE
RFE: Clickable pub keys

### ISSUE THREAD

**Issue by thejerrod** [cryptosharks131/lndg#37]
Having pubkeys resolve to a link wherever they show up would help with workflow, for example on suggested_opens/, it would be great to click and go to the node's amboss or 1ml

**Comment by cryptosharks131** [comment]
Hi, thanks for your suggestions.

Can you tell me what sections you would like to see a hyperlink added? It looks like the hyperlink is working on the Suggested Opens page already. Most pages should be using links already but may have missed some spots.

https://github.com/cryptosharks131/lndg/blob/master/gui/templates/open_list.html#L21
