### ISSUE TITLE
conflict: unable to remove repository reference on manual update from 1.7 to 1.8

### ISSUE THREAD

**Issue by smeisters** [cryptosharks131/lndg#371]
Hello!

When updateing manually from lndg 1.7 to 1.8 i get the following error. this used to work without any problem with previous versions via terminal: "sudo ~/umbrel/scripts/app update lndg"

But now i get the folliwng error and cannot find any solution to get around it.. can somebody provide some help for me here?

Error response from daemon: conflict: unable to remove repository reference "ghcr.io/cryptosharks131/lndg:v1.7.0@sha256:xxx" (must force) - container 59ba6aded2c7 is using its referenced image 91d8e4fae533

**Comment by cryptosharks131** [comment]
It seems like the container using the LNDg image is still running. See if you can check on the container status and stop it if its still running, then try to update again.
