### ISSUE TITLE
Security alert: HTML script injection into the user's browser.

### ISSUE THREAD

**Issue by JaviLib** [cryptosharks131/lndg#394]
When opening a channel with a node with html code inside, an injection happens. Try for example to open a channel with this node https://lightningnetwork.plus/nodes/03db10aa09ff04d3568b0621750794063df401e6853c79a21a83e1a3f3b5bfb0c8

As you can see, the name of the node is **<script>alert("LDK");</script>**, and when you click on channel of the node, an alert happens in the browser.

<img width="599" alt="imagen" src="https://github.com/user-attachments/assets/65d5ae24-b020-45c6-9afb-5f19dafead7d">

Also, the name of the node appears blank in the list of channels, like this:

<img width="637" alt="imagen" src="https://github.com/user-attachments/assets/bcfdfb19-ec53-4c9e-8b55-e1c18e3fad2e">

So.

The script executed in this example is not very harmful, but imagine somebody changes the name and inject a full harmful script into the users browsers. This can be very harmful.

Please, urgently release a patch.

**Comment by cryptosharks131** [comment]
This should now be resolved in the latest v1.9.0 branch. Can you verify if you are still able to replicate the issue with this branch?

**Comment by cryptosharks131** [comment]
duplicate: #363
