### ISSUE TITLE
Outbound% and Inbound% do not add up to 100 in main screen

### ISSUE THREAD

**Issue by asvdf** [cryptosharks131/lndg#4]
Every channel will end up with 99% total when summing outbound % and inbound %. No big deal, but is it possible you are using floor() for both instead of round()?

**Comment by cryptosharks131** [comment]
Thanks for your report, something similar to what you are describing is happening.  In this case, when the database divides two integers it forces the result to also be an integer.  This essentially results in a floor() result and loss of precision.

To address the issue, the precision in the database calculation was increased and the result is then later rounded and truncated to keep the value clean on the dashboard.

Related Commit: https://github.com/cryptosharks131/lndg/commit/aba53c3b4d6f69ad27ed82f27a75ef5d514fac70
