### ISSUE TITLE
GUI : Wrong redirection from /autopilot to /suggested_action 

### ISSUE THREAD

**Issue by hoplaaa** [cryptosharks131/lndg#41]
Being on /autopilot page, seeing the message :
Experimental. This will allow LNDg to automatically act upon the suggestions found [here](http://192.168.0.73:8889/suggested_actions).

`here `points to /suggested_actions instead of newly named : /actions

https://github.com/cryptosharks131/lndg/blob/ea83dd324aedddb6dc8a76b588e0cf4b2494bb4c/gui/templates/autopilot.html#L33

Bellow the definition of /actions page: 
https://github.com/cryptosharks131/lndg/blob/d3f20eda6224ba8f821116640d9896ded165e786/gui/urls.py#L41

**Comment by cryptosharks131** [comment]
Fix pushed to master, thanks for the report!
3274c17286bf9ef0b86d709b84849656dda7dbba
