### ISSUE TITLE
only displays details for 16 channels

### ISSUE THREAD

**Issue by pjw65** [cryptosharks131/lndg#42]
LNDg v1.0.2 on Umbrel 0.4.14-build-5542633 (lnd v0.14.2-beta) on Ubuntu 20.04 Desktop

The most resently opened channels are not displayed. 

Active Channels: 20 / 21
Lnd sync: True | chain sync: True | chain: "bitcoin" network: "mainnet" 

Active Channels (Details) displayed only for 16 (4 missing)
Inactive Channels (Details) displayed for 1 (correct)

After a while an inactive channel became active, but the Details page was not updated:

Active Channels: 21 / 21
Lnd sync: True | chain sync: True | chain: "bitcoin" network: "mainnet" 

Active Channels (Details) displayed only for 16 (5 missing)
Inactive Channels (Details) displayed for 1 (wrong)

What I would like to see:
- Details for all active channels
- if a channel is not any more inactive, it should disapear from this list

**Comment by cryptosharks131** [comment]
It sounds like something has stopped the data processor inside the LNDg container.

Can you try to manually restart the LNDg app? You can do this by logging into your node and running:

`~/umbrel/scripts/app stop lndg`
`~/umbrel/scripts/app start lndg`

**Comment by pjw65** [comment]
```
~/umbrel/scripts/app stop lndg
~/umbrel/scripts/app start lndg
```
did the job, thank you. 
Good workaround.

**Comment by cryptosharks131** [comment]
Great news. This issue is further mitigated in v1.0.3 (should be coming to Umbrel soon).
