### ISSUE TITLE
Wrong limit for base fee : 100sat instead of 100000sat

### ISSUE THREAD

**Issue by hoplaaa** [cryptosharks131/lndg#46]
100sat max base fee, it should be 100 000 sat  ie 100 000 000 msat, `max="100000000"`

https://github.com/cryptosharks131/lndg/blob/d3f20eda6224ba8f821116640d9896ded165e786/gui/templates/advanced.html#L61

**Comment by cryptosharks131** [comment]
This was an arbitrary limit I set in the early days to keep myself from doing something silly. You can override the value by changing the html tag in your browser and then submitting the value.

What is the purpose to charge over 100 sats in base fee? I'm not sure the true limit is 100 000 000 msat either.
