### ISSUE TITLE
Does LNDg have a logo?

### ISSUE THREAD

**Issue by VajraOfIndra** [cryptosharks131/lndg#52]
... or do you have plan to have one?

**Comment by cryptosharks131** [comment]
This logo is currently being used on a few platforms.
https://github.com/getumbrel/umbrel-apps-gallery/blob/master/lndg/icon.svg

**Comment by VajraOfIndra** [comment]
> This logo is currently being used on a few platforms. https://github.com/getumbrel/umbrel-apps-gallery/blob/master/lndg/icon.svg

Thank you
