### ISSUE TITLE
AR enable/disable doesn't save setting

### ISSUE THREAD

**Issue by ptgmc29** [cryptosharks131/lndg#53]
On main page or rebalancing page, toggling to ENABLE on AR does not save settings. 

Set AR for all channels does not save.

**Comment by cryptosharks131** [comment]
The AR-Enabled global setting does not set enabled on each channel, rather it just activates the tool. The enabled button on the channel level tells the system which channels to target for refilling.

There are some notes on the README page to help with understanding the AR tool better.
https://github.com/cryptosharks131/lndg#auto-rebalancer
