### ISSUE TITLE
Data Discrepancy? - Handling MPP

### ISSUE THREAD

**Issue by rbpaul** [cryptosharks131/lndg#54]
I have come across what appears to be a curious anomaly between the data retrieved from the payments api and the data retrieved from the paymentshops api.  I have found only this one instance, for a particular payment_hash.  

In the payments api, the total value of the payment is shown as 29,411 sats for a rebalance from MyChannel-A.  BUT the paymentshops data shows only 14,705 sats hoping from MyChannel-A to MyChannel-B for this payment_hash.  There is a 14,706 sats discrepancy!

I have poked about in my lnd data and come to find there is another series of hops associated with this payment_hash:  14,706 sats from MyChannel-C to NotMyChannel-X to MyChannel-B, which completes the total.   Can you speak to why this series of hops does not appear in LNDg paymenthops data?   

When I look at this payment_hash in the lnd payments.json, it shows this transaction failed at many attempts to pay 29,411 sats before the payment was split into one 14,705 sats payment and another 14,706 payment and processed from separate outgoing channels to the one incoming channel.  

As I have continued to poke, I am seeing more discrepancies like this between payments and paymenthops.  It usually doesn’t stick-out because the multiple payments for a single payment_hash have previously been generated from the same channel rather than separate channels.

**Comment by cryptosharks131** [comment]
Interesting, it seems very possible we are not handling multi-path payments correctly in the hop data then.

Would you be able to provide an example of the hops data that produces a discrepancy?

**Comment by rbpaul** [comment]
That is my thinking too.  I will be happy to provide what I can.  Can you be more specific as to what count as an example?  I already shared that I didn't find it in the hops data, but in my lnd payments json file after some time consuming poking.  So I could give you that particular payment_hash from that file.  Would there be anything there I should't share?  Would that help?

**Comment by cryptosharks131** [comment]
If you could share the data in the hops section of the payment, that should suffice. You can remove all the identifying information including channel ids and values if you like, mostly looking for just the structure of the data.

**Comment by rbpaul** [comment]
I was looking into LNDg to reconcile a discrepancy that I found with my spreadsheet.  I had attributed the totality of a split payment to one paying channel.  I resolved my discrepancy with understanding the split payment was being made with different channels.  I noticed that bos and LNDg were doing it the way I did before I noticed the issue. 

I updated my script at the suggestion of Alex, and thought you might like this information.   Looking for more than one “SUCCEDED” in the htlcs section of lnd listpayments json file revealed the issue to me.  I have found payments split into as many as three parts but not yet seen them split among more than two channels.   I don’t know how to get this information in the hops section.  I can try to answer more questions and provide more detail as I understand it.

**Comment by cryptosharks131** [comment]
Ah this is helpful, so you are saying that there are 2 successful htlcs both of which have their own set of hop data under this one payment. So LNDg is indeed missing one route of hop data for this payment in paymenthops?

It does appear that would be the result if there are more than one successful htlc.

**Comment by rbpaul** [comment]
Yes 2 (or more) successful htlcs in the payment.  I am coming to learn that is the definition of split payment.  It made no effect on my spreadsheet until the payment was split amount two or more channels.

**Comment by cryptosharks131** [comment]
Thanks, will try to address this scenario in an upcoming update.

**Comment by cryptosharks131** [comment]
Addressed in https://github.com/cryptosharks131/lndg/pull/63
