### ISSUE TITLE
Auto Rebalancer not acting

### ISSUE THREAD

**Issue by 941design** [cryptosharks131/lndg#55]
Running Version 1.0.3. on umbrel.

Followed instructions in README.md.

Initially, some unsuccessful rebalancing attempts were made, however after one iteration the rebalancer gave up permanently, i.e. it does no longer attempt **any** rebalancing.

Logs don't show anything of significance.

Appreciate any advice on how to approach the problem. Will be happy to provide more information, if attainable.

**Comment by cryptosharks131** [comment]
Are you sure the rebalancer has been setup with settings that will trigger under your current conditions? If there are no candidates for rebalancing based on your settings, it will not schedule anything for rebalance. More detail can be found on the README page.
https://github.com/cryptosharks131/lndg#auto-rebalancer

A nice feature in v1.0.4 is a rebalancing page that may help you to visualize which channels are currently candidates based on your current settings.

If you still feel like the settings are correct then please provide some details around a specific scenario where you think it should be rebalancing a target channel (liquidity%, iTarget%, oTarget%, etc.)

**Comment by 941design** [comment]
Hi,
with the `/rebalancing` page I was able to figure out the cause: No rebalancing attempts were made because the _fee ratio_ was too high.
I assume the intention is to avoid rebalancing attempts that encourage unprofitable behaviour.
However, it is not clear to me, how the _fee ratio_ is determined. Is it really that the entire node graph is searched for routes, and the potentially earned fees are compared to the cheapest rebalancing route?
