### ISSUE TITLE
Max Cost % per Channel and AR-MaxCost%

### ISSUE THREAD

**Issue by pjw65** [cryptosharks131/lndg#61]
I changed AR-MaxCost% in the Advanced Settings (Update Local Settings), but none of the settings in Max Cost % per Channel did change. 
I think this field is absolet.

I could change it for all channels using the "Update All Channel AR max Cost %s" (Tooltip Text), but it was hard to find, because there are a bunch of empty fields without names (Why not write on the left of them "Update for all Channels:").

**Comment by cryptosharks131** [comment]
This is intended in v1.0.5 as it allows you to update these settings without affecting all channels. You can now use the empty boxes at the top of the table to update all channel values from the Advanced Settings page.

`AR-MaxCost%`, `AR-Outbound%` and `AR-Target%` values don't have to align with each channel but they do dictate what settings a new channel open starts with.
