### ISSUE TITLE
Rebalance with no effect and high costs

### ISSUE THREAD

**Issue by ABAPRules** [cryptosharks131/lndg#68]
Had 2 Channels with same peer.
Both were enabled for Rebalancing since both had more incoming than outgoing liquidity.
After the smaller of the two channels fell below iTarget%, suddenly a lot of rebalancing payments occurred which were executed from the smaller to the larger channel.
The balance of the larger channel did not change, and the payments seem to have ended up back at the smaller channel?!
This therefore resulted in an infinite number of rebalancing payments which I fortunately noticed relatively quickly... but a few thousand sats for fees disappeared anyway.

**Comment by cryptosharks131** [comment]
Which version are you currently using?

A fix was pushed in v1.1.0 to address a similar issue, particularly when there were no eligible channels to push out with.

**Comment by ABAPRules** [comment]
I'am already using LNDg v1.1.1

**Comment by cryptosharks131** [comment]
Are you able to go to this page `/api/rebalancer/` and find the rebalances that you are referring to? You may need to search for it near the last pages of the api (newest records show at the end of the list)

**Comment by ABAPRules** [comment]
Since I had thousands of these rebalances i had no problem to find some of them under /api/rebalancer/:

Problem was between Channel-ID's 775016059624685569 (Small Channel = Rebalance Source) and 811049254803406849 (Big Channel = Rebalance Target)
Both channels exist between my node and PubKey 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 3174,
    "next": "http://192.168.1.58:8889/api/rebalancer/?limit=100&offset=1500",
    "previous": "http://192.168.1.58:8889/api/rebalancer/?limit=100&offset=1300",
    "results": [
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1401/",
            "id": 1401,
            "requested": "2022-05-25T08:23:24.087497",
            "start": "2022-05-25T08:23:24.112679",
            "stop": "2022-05-25T08:23:25.543451",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "09afca502951e7048e462752e596f3169351d8012b83275912c7319e0d2f0e20",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1402/",
            "id": 1402,
            "requested": "2022-05-25T08:23:25.698808",
            "start": "2022-05-25T08:23:26.207415",
            "stop": "2022-05-25T08:23:27.679890",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "77c826462edaa392efee9b140685097a2dc9a3bfe78e3b443d92c17497c11fc1",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1403/",
            "id": 1403,
            "requested": "2022-05-25T08:23:27.938747",
            "start": "2022-05-25T08:23:27.963561",
            "stop": "2022-05-25T08:23:29.242804",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "81c5d2fed834ec923e12212bfc0e12266e2f01e59e7e0772475d9b99f25be9f7",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1404/",
            "id": 1404,
            "requested": "2022-05-25T08:23:29.420918",
            "start": "2022-05-25T08:23:29.483221",
            "stop": "2022-05-25T08:23:31.006442",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "0b5ce4e3902c6aa6f4f34b02edc880c363b10af52f3ad68048d96278711879ff",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1405/",
            "id": 1405,
            "requested": "2022-05-25T08:23:31.199630",
            "start": "2022-05-25T08:23:31.226394",
            "stop": "2022-05-25T08:23:32.656713",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "d0086c7f8efdfdaff2aa6a02f60cb893546f312bc62c611703a63fc5900ad012",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1406/",
            "id": 1406,
            "requested": "2022-05-25T08:23:32.843036",
            "start": "2022-05-25T08:23:32.870285",
            "stop": "2022-05-25T08:23:34.259079",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "f72333f3d12701645a88391dc9b1fe1f0977edf4670d9638db02554f527e797a",
            "manual": false
        },
        {
            "url": "http://192.168.1.58:8889/api/rebalancer/1407/",
            "id": 1407,
            "requested": "2022-05-25T08:23:34.414030",
            "start": "2022-05-25T08:23:34.475256",
            "stop": "2022-05-25T08:23:35.967264",
            "status": 2,
            "value": 19110,
            "fee_limit": 12,
            "outgoing_chan_ids": "[775016059624685569, 793050249392029697, 793825405030170625, 801446120241954817, 804644599519444992, 804646798558232577, 804898586793213953]",
            "last_hop_pubkey": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
            "target_alias": "ACINQ",
            "duration": 1,
            "payment_hash": "d785d1a90bd50fa8045f819e3daa603a5e9e4374ea2eb4013b9b3ee1a64ae981",
            "manual": false
        },

**Comment by cryptosharks131** [comment]
It appears that `775016059624685569` is currently not enabled for AR targeting on the dashboard (and seems like `811049254803406849` is enabled), which would allow `775016059624685569` to be used as a source.

Can you confirm the rebalancer settings for these two channels?

**Comment by cryptosharks131** [comment]
You can check your last settings on the channel by finding it in the Closure tab and clicking the channel ID.

You can also navigate to the channel card directly.
`/channel?=775016059624685569`

**Comment by cryptosharks131** [comment]
When you have two channels to the same peer, you cannot control which channel is used on the last hop, the peer gets this control. If they want to send everything down the smaller channels until its empty on their side, then move to the larger channel, they can.

If you do have two channels to the same peer, make sure both channels have the same settings and/or set the oTarget% to 100 so that it can never be used as a source.

**Comment by ABAPRules** [comment]
This explains why the rebalance-lnd i used before considered the outbound and inbound sum of the two channels together and always performed the rebalancing in sum per peer. 
Wouldn't it make sense then to synchronize the control of the "AR" buttons in lndg for identical peer across all channels or at least to prevent rebalancing from within the same peer?!

**Comment by ABAPRules** [comment]
By the way... Thanks for your support!

**Comment by cryptosharks131** [comment]
You can control it in the beginning since the amounts will only work one way (new channels starts full and old is empty) but at any given point later that may or may not be true.

If a drain opens to you, this does seem possible, though maybe an unlikely situation.  That being said, I see the concern here, I am just not sure what the right solution is yet.

You certainly can keep your settings to default oTarget% to 100 for new channels in the mean time if you are worried about it happening again.

**Comment by ABAPRules** [comment]
Is the default Setting for oTarget% = 100 set via "Advanced Settings" -> "Update Local Settings" -> AR-Outbound% = 1 or how do i achieve this?

**Comment by ABAPRules** [comment]
Possible solution might be to set an extra Flag "Yes, I want to rebalance within the same peer and am aware that the peer has control over which channel the sats end up in.".
If Flag ist not set = No Rebalancing within same peer.

**Comment by cryptosharks131** [comment]
> Is the default Setting for oTarget% = 100 set via "Advanced Settings" -> "Update Local Settings" -> AR-Outbound% = 1 or how do i achieve this?

That's right!
