### ISSUE TITLE
alow to set a minimum ppm fee

### ISSUE THREAD

**Issue by pjw65** [cryptosharks131/lndg#73]
I use AR-Autofees = 1
For some channels, the fee will be set to 0 ppm  (I use everwhere 0 base fee).
I would like to have a minimum fee of 50 ppm.
Would be nice, if I could set this in the coinfiguration.
Don't know if it would also make sence to set a max. fee.

**Comment by ursus-caerulus** [comment]
Would like this feature as well!
I combine minimum fee with min htlc, so that the minimum fee is at least 1 sat.

**Comment by soulBit** [comment]
Adding some support for this here rather than just pestering NgU on Telegram ;) I would love this feature too, either a global setting or ability to customize it per channel

**Comment by 2Fast2BCn** [comment]
> Adding some support for this here rather than just pestering NgU on Telegram ;) I would love this feature too, either a global setting or ability to customize it per channel

A global setting for ALL channels already exist ;-)
