### ISSUE TITLE
Logging steps to migrate from sqlite to postgres

### ISSUE THREAD

**Issue by TrezorHannes** [cryptosharks131/lndg#78]
## Implemented this on two different nodes - follow at your own risk
Just logging the steps here to carefully record what needs to be done to migrate from LNDg sqlite to postgres. This is for advanced users, and I just want to kick off the convo here with ngu to ensure all grounds are covered properly

### Preparation

- check your `locale` is set to `LANG=en_US.UTF-8` 

#### Postgress
- install postgres with `sudo apt install postgresql`
- login via `sudo su - postgres` and check `locale` again to ensure your global settings are not tricking you for all you non-US users out there
- login to postgres with `psql` and create the database
`create user lndg;create database lndg LOCALE 'en_US.UTF-8' TEMPLATE template0;alter role lndg with password '<psql_password>';grant all privileges on database lndg to lndg;alter database lndg owner to lndg;`
- exit with `\q`
- exit from postgres user, back to your main-user

#### Additional Requirements
- `cd lndg`
- `sudo .venv/bin/pip install --upgrade setuptools`
- `sudo apt install libpq-dev`
- `.venv/bin/pip install psycopg2`

### Exectution
- Stop lndg systemctl services
`sudo systemctl stop htlc-stream-lndg.service && sudo systemctl stop rebalancer-lndg.timer && sudo systemctl stop jobs-lndg.timer`
- adjust database connections: `cd lndg` and `nano lndg/settings.py`

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lndg',
        'USER': 'lndg',
        'PASSWORD': '<psql_password>',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
```
- Dump your existing data into a jason file
`cd lndg && .venv/bin/python manage.py dumpdata gui.channels gui.peers gui.rebalancer gui.localsettings gui.autopilot gui.autofees gui.failedhtlcs > dump.json`
- `.venv/bin/python manage.py migrate`

#### Remove some noise
```
.venv/bin/python manage.py shell
from django.contrib.contenttypes.models import ContentType
ContentType.objects.all().delete()
exit()
```

#### Import
- import dump data into postgres: `.venv/bin/python manage.py loaddata dump.json`
- recreate your login user with data from lndg/data/lndg-admin.txt: `.venv/bin/python manage.py createsuperuser`
- user: lndg-admin
- pwd: `cat lndg/data/lndg-admin.txt`

#### Tiny adjustments
- `nano jobs.py`
- Required temporary change for payment/invoice messages on lines 52, 93, 112 of jobs.py (find/replace in nano via ALT-R)
.decode('utf-8', errors='ignore')
.decode('utf-8', errors='ignore').replace("\x00", "\uFFFD")

#### Put it together
- Restart uwsgi via `sudo systemctl restart uwsgi`
- Start all lndg-background services: `sudo systemctl start htlc-stream-lndg.service && sudo systemctl start rebalancer-lndg.timer && sudo systemctl start jobs-lndg.timer`

### Verify & Conclude
Login to your GUI and verify all is working
- tables payments and invoices may need some time repopulating. Those haven't been migrated
- in case for my instance, I had 60,000 entries, so it's running backwards from 8 months and took 1.5hrs. If you have a slow machine, this is going to take a long time (couple of hours, at least)

**Comment by cryptosharks131** [comment]
Also was required for compilation of psycopg2:  `sudo apt install gcc python3-dev`

Was able to create a database without template or LOCALE data.
`create user lndg;create database lndg;alter role lndg with password '<psql_password>';grant all privileges on database lndg to lndg;alter database lndg owner to lndg;`
