### ISSUE TITLE
/route?= does not work randomly

### ISSUE THREAD

**Issue by BhaagBoseDK** [cryptosharks131/lndg#85]
I noticed (appears to be random) that clicking on successful rebalance sometimes does not show the route. It does not appear to be linked to peer pairs. 

The payment route is available in lncli and the payment is also available in lncli. However, in LNDg the "out" payment is not visible; therefore, the path/hops are also not visible.

It only happens at certain times randomly.

**Comment by BhaagBoseDK** [comment]
Could this be a race condition due to this in jobs.py
```
    #Remove anything in-flight so we can get most up to date status
    Payments.objects.filter(status=1).delete()
```

**Comment by cryptosharks131** [comment]
The chan_out field can be `null` but should be filled in normally when the status is `2`.

Only one thread of jobs.py should be running at a time so there should not be a race condition here. This is also on the payment table and not the payment hop table. Is the payment data missing from both datasets?

I have been unable to replicate this issue so far to help investigate further. Could you try checking the API for the payment record you see missing route data for on the `/api/payments` page? You should be able to take that same payment hash from the record and place it at the end of this URI to pull any successful route.
`/route?=<payment_hash>`

**Comment by BhaagBoseDK** [comment]
Even I have not been able to find another instance of this issue. Will do the above in the next instance.

**Comment by BhaagBoseDK** [comment]
I have not seen the reoccurrence of this issue. Maybe it was due to jobs.py playing up. It can be closed.

**Comment by BhaagBoseDK** [comment]
Had it again today

Payment hash exist in lnd but not visible in route.

f7e00ec1980f1be155ecb0818e1c46a97cd8f49a6835b6bb26430136e13fb2a4

umbrel@umbrel:~/umbrel/app-data/bluewallet $ bos call
? Select method to call getPayment
[id] Payment hex encoded payment hash f7e00ec1980f1be155ecb0818e1c46a97cd8f49a6835b6bb26430136e13fb2a4

is_confirmed: true
is_failed:    false
is_pending:   false
payment: 
  destination:  03c5528c628681aa17ab9e117aa3ee6f06c750dfb17df758ecabcd68f1567ad8c1
  confirmed_at: 2022-07-27T08:53:25.976Z
  created_at:   2022-07-27T08:35:28.653Z
  fee:          392
  fee_mtokens:  392966
  hops:

**Comment by BhaagBoseDK** [comment]
@cryptosharks131 how does one re open the issue

**Comment by BhaagBoseDK** [comment]
OK I understand the issue now
Payment Index i1 = 1136242 started at time t=0 (08:35) but took 17 minutes to complete. t=x (08:53). This was lndg rebalance.

Payment Index i2 = 1136270 started at time t=1 (08:37) but completed within a few minutes t=y (08:39). This was my own rebalanc however it can easily be a payment made manually which completed before an ongoing lndG rebalance.

since y < x, while i2>i1, jobs.py will only fetch > i2 in subsequent runs. Therefore it will never get the new status for i1. 

Looks like     `Payments.objects.filter(status=1).delete()` is the culprit but even removing this would not solve the issue because at t=y, the max index would be updated to i2 while i1 is still in flight.

**Comment by cryptosharks131** [comment]
`Payments.objects.filter(status=1).delete()` should just remove things that are in-flight which should make sure we always get the last status (success/fail).

**Comment by BhaagBoseDK** [comment]
> `Payments.objects.filter(status=1).delete()` should just remove things that are in-flight which should make sure we always get the last status (success/fail).

yes but imagine at time t>y<x in my example, index i1 will be deleted BUT will not be fetched again.

**Comment by BhaagBoseDK** [comment]
Other option could be to use min(index) where status ==1 in jobs.py to fetch future payments.

**Comment by BhaagBoseDK** [comment]
PR #117 pushed
