### ISSUE TITLE
Auto Pilot : Take all channels for a peer into account while enable/disable AR

### ISSUE THREAD

**Issue by BhaagBoseDK** [cryptosharks131/lndg#90]
Current Autopilot works on the individual channels which can use one of the channels to be enabled or disabled for AR. While rebalancing there is no control on which channel is used for rebalancing if there are multiple channels with a peer since only pubkey is used in last hop and peer system decides which channel to use.

Autopilot should use combined capacity/inbound/outbound for a channel to enable/disable AR.

**Comment by BhaagBoseDK** [comment]
Pull Request #91

**Comment by cryptosharks131** [comment]
#94
