### ISSUE TITLE
Don't try Manual Installation with Umbrel 0.5 or higer

### ISSUE THREAD

**Issue by phil71x** [cryptosharks131/lndg#99]
Hi,

I've just installed LNDg. Followed procedure  "Manual install with Umbrel".
When I tried to log for the first time, the following error message shows:

An error has occured!
Error Code: [Errno 2] No such file or directory: '/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
LNDg v1.2.1

I'm running Umbrel 0.5.1

Looking forward to your guidance!

**Comment by phil71x** [comment]
I've found the directory in two places :

 /home/umbrel/umbrel/app-data/lightning/data/lnd/data/chain/bitcoin/mainnet
/mnt/data/umbrel/app-data/lightning/data/lnd/data/chain/bitcoin/mainnet

**Comment by phil71x** [comment]
It looks like rebalance-lnd is broken following the installation of LNDg.

The following error message is appearing when trying to rebalance :
FileNotFoundError: [Errno 2] No such file or directory: '/home/umbrel/umbrel/lnd/tls.cert'

**Comment by phil71x** [comment]
Please add "Don't try with Umbrel version 0.5 and higher"

**Comment by cryptosharks131** [comment]
Thanks for the updates, it seems the recent Umbrel v0.5 has brought many changes. You can also install LNDg directly from the app store with Umbrel which is probably the preferred methods these days.
